spring.application.name=studentapp


# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://192.168.123.1:5432/std_registration
spring.datasource.username=postgres
spring.datasource.password=ravi123

# JPA Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=registration
